%% check_metrics

check_angleB_tree
check_cvol_tree
check_cyl_tree
check_dstats_tree
check_eucl_tree
check_flatten_tree
check_flip_tree
check_len_tree
check_morph_tree
check_rot_tree
check_scale_tree
check_surf_tree
check_tran_tree
check_vol_tree
check_zcorr_tree
check_sholl_tree
check_stats_tree

